SET CLUSTER '';
SET DEFAULT_TABLE_TYPE 0;
SET WRITE_DELAY 500;
SET DEFAULT_LOCK_TIMEOUT 2000;
SET CACHE_SIZE 16384;
CREATE USER IF NOT EXISTS SA SALT 'e8a8cc9606ea5029' HASH '88fe6ce5dca4e22f9ddeead099e110de1afa892b4b18e6af38df4150ec4a8f31' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_670936A6_C2FC_4E36_917D_FE2C7550EDE9 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AA937065_7230_4C4A_92C1_56846D33499A START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02D4FE4E_92A3_46CE_AB65_710DE088054B START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.COLLECTIONS(
    ID_COLLECTION INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_02D4FE4E_92A3_46CE_AB65_710DE088054B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02D4FE4E_92A3_46CE_AB65_710DE088054B,
    NAME VARCHAR(100) NOT NULL,
    NRGRAMS INTEGER NOT NULL,
    FORMAT VARCHAR(3) NOT NULL,
    GRAMS LONGVARBINARY
);
ALTER TABLE PUBLIC.COLLECTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_EE PRIMARY KEY(ID_COLLECTION);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COLLECTIONS;
CREATE CACHED TABLE PUBLIC.AUTHORS(
    ID_AUTHOR INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AA937065_7230_4C4A_92C1_56846D33499A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AA937065_7230_4C4A_92C1_56846D33499A,
    NAME VARCHAR(50) NOT NULL,
    ID_COLLECTION INTEGER NOT NULL
);
ALTER TABLE PUBLIC.AUTHORS ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID_AUTHOR);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AUTHORS;
CREATE INDEX PUBLIC.MERGEAUTHORS ON PUBLIC.AUTHORS(NAME);
CREATE CACHED TABLE PUBLIC.DOCUMENTS(
    ID_DOC INTEGER NOT NULL,
    ID_COLLECTION INTEGER NOT NULL,
    TYPE INTEGER,
    TITLE LONGVARCHAR,
    RESEARCH_ADDRESS LONGVARCHAR,
    ABSTRACT LONGVARCHAR,
    KEYWORDS LONGVARCHAR,
    REFERENCES LONGVARCHAR,
    YEAR INTEGER NOT NULL,
    TIMES_CITED INTEGER,
    DOI VARCHAR(50),
    FIRST_PAGE VARCHAR(20),
    END_PAGE VARCHAR(20),
    PDF_FILE VARCHAR(200),
    JOURNAL VARCHAR(200),
    JOURNAL_ABBREV VARCHAR(100),
    VOLUME VARCHAR(30),
    CLASS INTEGER DEFAULT 0
);
ALTER TABLE PUBLIC.DOCUMENTS ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID_DOC, ID_COLLECTION);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTS;
CREATE INDEX PUBLIC.MERGECOREREFERENCES ON PUBLIC.DOCUMENTS(JOURNAL_ABBREV, YEAR, VOLUME, FIRST_PAGE, ID_COLLECTION);
CREATE CACHED TABLE PUBLIC.NGRAMS(
    ID_DOC INTEGER NOT NULL,
    ID_COLLECTION INTEGER NOT NULL,
    GRAMS LONGVARBINARY
);
ALTER TABLE PUBLIC.NGRAMS ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID_DOC, ID_COLLECTION);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NGRAMS;
CREATE CACHED TABLE PUBLIC.CITATIONS(
    ID_CITATION INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_670936A6_C2FC_4E36_917D_FE2C7550EDE9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_670936A6_C2FC_4E36_917D_FE2C7550EDE9,
    ID_COLLECTION INTEGER NOT NULL,
    TYPE VARCHAR(10),
    ID_AUTHOR INTEGER,
    YEAR INTEGER,
    JOURNAL VARCHAR(100),
    VOLUME VARCHAR(30),
    CHAPTER VARCHAR(30),
    DOI VARCHAR(70),
    PAGES VARCHAR(20),
    ARTN VARCHAR(20),
    FULL_REFERENCE LONGVARCHAR,
    ID_DOC_CORE INTEGER
);
ALTER TABLE PUBLIC.CITATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID_CITATION);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CITATIONS;
CREATE INDEX PUBLIC.MERGEREFERENCES ON PUBLIC.CITATIONS(YEAR, PAGES, ID_AUTHOR, VOLUME, JOURNAL);
CREATE CACHED TABLE PUBLIC.DOCUMENTS_TO_REFERENCES(
    ID_DOC INTEGER NOT NULL,
    ID_COLLECTION INTEGER NOT NULL,
    ID_REFERENCE INTEGER NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTS_TO_REFERENCES;
CREATE CACHED TABLE PUBLIC.DOCUMENTS_TO_CITATIONS(
    ID_DOC INTEGER NOT NULL,
    ID_COLLECTION INTEGER NOT NULL,
    ID_CITATION INTEGER NOT NULL
);
ALTER TABLE PUBLIC.DOCUMENTS_TO_CITATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID_DOC, ID_COLLECTION, ID_CITATION);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTS_TO_CITATIONS;
CREATE CACHED TABLE PUBLIC.DOCUMENTS_TO_AUTHORS(
    ID_DOC INTEGER NOT NULL,
    ID_COLLECTION INTEGER NOT NULL,
    ID_AUTHOR INTEGER NOT NULL,
    AUTHOR_ORDER INTEGER NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTS_TO_AUTHORS;
ALTER TABLE PUBLIC.COLLECTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_E UNIQUE(NAME);
ALTER TABLE PUBLIC.DOCUMENTS_TO_AUTHORS ADD CONSTRAINT PUBLIC.CONSTRAINT_98 FOREIGN KEY(ID_AUTHOR) REFERENCES PUBLIC.AUTHORS(ID_AUTHOR) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.DOCUMENTS_TO_CITATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B5B FOREIGN KEY(ID_CITATION) REFERENCES PUBLIC.CITATIONS(ID_CITATION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.NGRAMS ADD CONSTRAINT PUBLIC.CONSTRAINT_89 FOREIGN KEY(ID_DOC, ID_COLLECTION) REFERENCES PUBLIC.DOCUMENTS(ID_DOC, ID_COLLECTION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.DOCUMENTS_TO_CITATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B5 FOREIGN KEY(ID_DOC, ID_COLLECTION) REFERENCES PUBLIC.DOCUMENTS(ID_DOC, ID_COLLECTION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.DOCUMENTS ADD CONSTRAINT PUBLIC.CONSTRAINT_DE FOREIGN KEY(ID_COLLECTION) REFERENCES PUBLIC.COLLECTIONS(ID_COLLECTION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.AUTHORS ADD CONSTRAINT PUBLIC.CONSTRAINT_44 FOREIGN KEY(ID_COLLECTION) REFERENCES PUBLIC.COLLECTIONS(ID_COLLECTION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.DOCUMENTS_TO_AUTHORS ADD CONSTRAINT PUBLIC.CONSTRAINT_9 FOREIGN KEY(ID_DOC, ID_COLLECTION) REFERENCES PUBLIC.DOCUMENTS(ID_DOC, ID_COLLECTION) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.CITATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_3C FOREIGN KEY(ID_COLLECTION) REFERENCES PUBLIC.COLLECTIONS(ID_COLLECTION) ON DELETE CASCADE NOCHECK;
