package topicevolutionvis.wizard;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import topicevolutionvis.data.*;
import topicevolutionvis.database.CollectionManager;
import topicevolutionvis.database.DatabaseCorpus;
import topicevolutionvis.projection.ProjectionData;
import topicevolutionvis.util.SystemPropertiesManager;
import topicevolutionvis.utils.filefilter.*;
import topicevolutionvis.wizard.WizardPanel;

/**
 *
 * @author Aretha
 */
public class DataSourceChoiceWizard extends WizardPanel implements ActionListener
{
    private ProjectionData pdata;
    
    private DatabaseImporter importer = null;
    
    private CollectionManager collectionManager;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton cancelButton;
    private JTextField collectionnameTextField;
    private JComboBox<String> corpusComboBox;
    private JTextField filenameTextField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JButton loadButton;
    private JTextField name_collection;
    private JTextField ngrams;
    private JComboBox nrgramsComboBox;
    private JLabel nrgramsLabel;
    private JTextField number_documents;
    private JTextField number_references;
    private JButton removeButton;
    private JCheckBox removeStopwordsByTaggingCheckBox;
    private JButton searchButton;
    private JLabel statusLabel;
    private JProgressBar statusProgressBar;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form DataSourceChoice
     */
    public DataSourceChoiceWizard(ProjectionData pdata) {
        this.pdata = pdata;
        initComponents();
        collectionManager = new CollectionManager();
        this.updateCollections("");
    }

    private void updateCollections(String collection) {
        String index = null;
        corpusComboBox.removeAllItems();
        ArrayList<String> collections = collectionManager.getCollections();
        corpusComboBox.addItem("Select...");
        for (String col : collections) {
            this.corpusComboBox.addItem(col);
            if (collection.equalsIgnoreCase(col)) {
                index = col;
            }
        }
        if (collection.equalsIgnoreCase("")) {
            corpusComboBox.setSelectedIndex(0);
        }
        if (index != null) {
            corpusComboBox.setSelectedItem(index);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        filenameTextField = new JTextField();
        jLabel1 = new JLabel();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        collectionnameTextField = new JTextField();
        nrgramsLabel = new JLabel();
        nrgramsComboBox = new JComboBox();
        removeStopwordsByTaggingCheckBox = new JCheckBox();
        jPanel4 = new JPanel();
        statusProgressBar = new JProgressBar();
        statusLabel = new JLabel();
        searchButton = new JButton();
        jPanel5 = new JPanel();
        loadButton = new JButton();
        cancelButton = new JButton();
        jPanel2 = new JPanel();
        corpusComboBox = new JComboBox<String>();
        removeButton = new JButton();
        jPanel6 = new JPanel();
        jPanel7 = new JPanel();
        jLabel6 = new JLabel();
        name_collection = new JTextField();
        jLabel7 = new JLabel();
        ngrams = new JTextField();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        number_documents = new JTextField();
        number_references = new JTextField();

        setBorder(BorderFactory.createTitledBorder("Choose the Data Source"));
        setLayout(new GridBagLayout());

        jPanel1.setBorder(BorderFactory.createTitledBorder("Load Document Collection"));
        jPanel1.setLayout(new GridBagLayout());

        filenameTextField.setColumns(30);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.insets = new Insets(4, 4, 4, 4);
        jPanel1.add(filenameTextField, gridBagConstraints);

        jLabel1.setText("File:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel3.setBorder(BorderFactory.createTitledBorder("Parameters"));
        jPanel3.setLayout(new GridBagLayout());

        jLabel2.setText("Collection name:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel3.add(jLabel2, gridBagConstraints);

        collectionnameTextField.setColumns(30);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel3.add(collectionnameTextField, gridBagConstraints);

        nrgramsLabel.setText("Number of Grams:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(6, 6, 6, 6);
        jPanel3.add(nrgramsLabel, gridBagConstraints);

        nrgramsComboBox.setModel(new DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(6, 6, 6, 6);
        jPanel3.add(nrgramsComboBox, gridBagConstraints);

        removeStopwordsByTaggingCheckBox.setText("Remove terms tagged as verbs, conjunctions ...");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(removeStopwordsByTaggingCheckBox, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(BorderFactory.createTitledBorder("Status"));
        jPanel4.setLayout(new GridBagLayout());

        statusProgressBar.setPreferredSize(new Dimension(400, 14));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(2, 2, 2, 2);
        jPanel4.add(statusProgressBar, gridBagConstraints);

        statusLabel.setText("");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(2, 2, 2, 2);
        jPanel4.add(statusLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(jPanel4, gridBagConstraints);

        searchButton.setText("Search ...");
        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(searchButton, gridBagConstraints);

        loadButton.setText("Load");
        loadButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        jPanel5.add(loadButton);

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel5.add(cancelButton);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 18, 82, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(BorderFactory.createTitledBorder("Collection already loaded into the database"));
        jPanel2.setLayout(new BorderLayout());

        corpusComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                corpusComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(corpusComboBox, BorderLayout.CENTER);

        removeButton.setText("Remove");
        removeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removeButton, BorderLayout.EAST);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 454;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(28, 18, 0, 0);
        add(jPanel2, gridBagConstraints);
       
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(7, 6, 0, 18);
        add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(BorderFactory.createTitledBorder("Informations"));
        jPanel7.setLayout(new GridBagLayout());

        jLabel6.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel6.setText("Nome Collection");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        jPanel7.add(jLabel6, gridBagConstraints);

        name_collection.setEditable(false);
        name_collection.setText("jTextField1");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.6;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(name_collection, gridBagConstraints);

        jLabel7.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel7.setText("NGrams");
        jLabel7.setHorizontalTextPosition(SwingConstants.LEFT);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        jPanel7.add(jLabel7, gridBagConstraints);

        ngrams.setEditable(false);
        ngrams.setText("jTextField2");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.3;
        jPanel7.add(ngrams, gridBagConstraints);

        jLabel8.setText("Number Of Documents");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        jPanel7.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Number Of References");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        jPanel7.add(jLabel9, gridBagConstraints);

        number_documents.setEditable(false);
        number_documents.setText("jTextField3");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.3;
        jPanel7.add(number_documents, gridBagConstraints);

        number_references.setEditable(false);
        number_references.setText("jTextField4");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.3;
        jPanel7.add(number_references, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        add(jPanel7, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        SystemPropertiesManager m = SystemPropertiesManager.getInstance();
        String directory = m.getProperty("COLLECTIONS.DIR");
        if (directory != null) {
            fc.setCurrentDirectory(new File(directory));
        } else {
            fc.setCurrentDirectory(new File("."));
        }
        SupportedFormatsCollections generalFilter = new SupportedFormatsCollections();
        fc.addChoosableFileFilter(generalFilter);
        fc.addChoosableFileFilter(new BibTeXFileFilter());
        fc.addChoosableFileFilter(new ISIFileFilter());
        fc.addChoosableFileFilter(new EndnoteExportFileFilter());
        fc.addChoosableFileFilter(new DatabaseFileFilter());
        fc.setFileFilter(generalFilter);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            filenameTextField.setText(file.getAbsolutePath());
            filenameTextField.setCaretPosition(0);
            this.collectionnameTextField.setText(file.getName().substring(0, file.getName().indexOf(".")));
            m.setProperty("COLLECTIONS.DIR", fc.getSelectedFile().getParent());
        }
}//GEN-LAST:event_searchButtonActionPerformed

    private void removeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (this.corpusComboBox.getSelectedIndex() > 0) {
           String collection = (String) this.corpusComboBox.getSelectedItem();
            collectionManager.removeCollection(collection);
            this.corpusComboBox.removeItem(collection);
        } else {
            JOptionPane.showMessageDialog(this, "A collection must be selected.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    public void setStatus(String status, boolean running) {
        this.statusLabel.setText(status);
        this.statusProgressBar.setIndeterminate(running);
    }

    private void loadButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        String collectionName = this.collectionnameTextField.getText().trim();
        String filename = this.filenameTextField.getText().trim();
        if (filename.compareTo("") != 0 && collectionName.compareTo("") != 0) {
            this.pdata.setSourceFile(filename);
            String corpusType = filename.substring(filename.lastIndexOf(".") + 1);
            int nrGrams = Integer.valueOf((String) this.nrgramsComboBox.getSelectedItem()).intValue();
            if (corpusType.compareTo("bib") == 0) {
                BibTeX2RIS bib = null;
                bib = new BibTeX2RIS();
                bib.setInputFile(new File(filename));
                bib.readData();
                bib.convert();
                importer = new ISICorpusDatabaseImporter(bib.getOutputFile().getAbsolutePath(), collectionName, nrGrams, this, removeStopwordsByTaggingCheckBox.isSelected());
            } else if (corpusType.compareTo("isi") == 0) {
                importer = new ISICorpusDatabaseImporter(filename, collectionName, nrGrams, this, removeStopwordsByTaggingCheckBox.isSelected());
            } else if (corpusType.compareTo("enw") == 0) {
                importer = new EndnoteDatabaseImporter(filename, collectionName, nrGrams, this, removeStopwordsByTaggingCheckBox.isSelected());
            } else if (corpusType.compareTo("db") == 0) {
                importer = new DumpDatabaseImporter(filename, this, removeStopwordsByTaggingCheckBox.isSelected());
            }

            if (importer != null) {
                this.cancelButton.setEnabled(true);
                this.setStatus("Loading collection " + collectionName + "...", true);
                this.loadingCollection();
                importer.execute();
            }

        } else {
            JOptionPane.showMessageDialog(this, "All parameters must be filled to load a new collection", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.importer.cancel(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void corpusComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_corpusComboBoxActionPerformed
        String selected_item;
        selected_item = (String) this.corpusComboBox.getSelectedItem();
        if (selected_item != null){
            try {
                getInformations(selected_item);
            } catch (IOException ex) {
                Logger.getLogger(DataSourceChoiceWizard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    private void loadingCollection() {
        this.loadButton.setEnabled(false);
        this.filenameTextField.setEnabled(false);
        this.collectionnameTextField.setEnabled(false);
        this.searchButton.setEnabled(false);
        this.nrgramsComboBox.setEnabled(false);
        this.removeButton.setEnabled(false);
    }

    public void finishedLoadingCollection(String collection, boolean canceled) {
        if (! canceled) {
            this.updateCollections(collection);
            this.filenameTextField.setText(null);
            this.collectionnameTextField.setText(null);
            this.cancelButton.setEnabled(false);
        }
        this.filenameTextField.setEnabled(true);
        this.collectionnameTextField.setEnabled(true);
        this.searchButton.setEnabled(true);
        this.nrgramsComboBox.setEnabled(true);
        this.loadButton.setEnabled(true);
        this.removeButton.setEnabled(true);
    }

    public DataSourceChoiceWizard reset() {
        return this;
    }

    @Override
    public void refreshData() {
        String collectionName = (String) this.corpusComboBox.getSelectedItem();
        if (collectionName.compareToIgnoreCase("Select...") != 0) {
            this.pdata.setCollectionName(collectionName);

        }

    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private void getInformations(String collectionName) throws IOException {
        if (collectionName != null && (collectionName.equals("Select...") || collectionName.isEmpty())){
            this.name_collection.setText("");
            this.ngrams.setText("");
            this.number_documents.setText("");
            this.number_references.setText("");
         } else {
            DatabaseCorpus corpus = new DatabaseCorpus(collectionName); 
            Integer ngrams = corpus.getNumberGrams();
            Integer numberDocs = corpus.getNumberOfDocuments();
            Integer numberRef = corpus.getNumberOfUniqueReferences();
            this.name_collection.setText(collectionName);
            this.ngrams.setText(ngrams.toString());
            this.number_documents.setText(numberDocs.toString());
            this.number_references.setText(numberRef.toString());
            pdata.setCollectionName(collectionName);
         }
    }

	@Override
	public boolean isNextStepTerminal() {
		return false;
	}

	@Override
	public boolean canGoToNextStep() {
       if (pdata.getCollectionName() != null) {
            pdata.setDatabaseCorpus(new DatabaseCorpus(pdata.getCollectionName()));
            return true;
       }
       return false;
	}

	@Override
	public boolean canGoToPreviousStep() {
		return true;
	}

	@Override
	public boolean hasPreviousStep() {
		return true;
	}

	@Override
	public boolean canCancel() {
		return true;
	}

	@Override
	public void cancel() {
	}

	@Override
	public boolean canResetConfiguration() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void resetConfiguration() {
		// TODO Auto-generated method stub
		
	}
}
