/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TagCloudPanel.java
 *
 * Created on 25/07/2011, 17:30:40
 */
package slider;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.font.FontRenderContext;
import java.awt.font.TextAttribute;
import java.awt.font.TextLayout;
import java.text.AttributedCharacterIterator;
import java.text.AttributedString;
import java.util.Hashtable;

/**
 *
 * @author Aretha
 */
public class TagCloudPanel extends javax.swing.JPanel {

    /** Creates new form TagCloudPanel */
    public TagCloudPanel() {
        initComponents();
        this.setBackground(Color.white);
    }
    // The LineBreakMeasurer used to line-break the paragraph.
//    private LineBreakMeasurer lineMeasurer;
//    // index of the first character in the paragraph.
//    private int paragraphStart;
//    // index of the first character after the end of the paragraph.
//    private int paragraphEnd;
    private static final Hashtable<TextAttribute, Object> map = new Hashtable<>();

    static {
        map.put(TextAttribute.FAMILY, "Arial");
        map.put(TextAttribute.SIZE, new Float(18.0));
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2;
        g2 = (Graphics2D) g;
        this.setBackground(Color.WHITE);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);

        Font f1 = new Font("Times", Font.BOLD, 24);
        AttributedString ats = new AttributedString("The  Starry  Night");
        Font f2 = new Font("Times", Font.BOLD, 10);
        ats.addAttribute(TextAttribute.FONT, f1, 0, 11);
        ats.addAttribute(TextAttribute.FONT, f2, 12, 18);
        AttributedCharacterIterator iter = ats.getIterator();

        FontRenderContext frc = g2.getFontRenderContext();
        TextLayout tl = new TextLayout(iter, frc);
        g2.setColor(Color.gray);
        g2.setComposite(java.awt.AlphaComposite.getInstance(java.awt.AlphaComposite.SRC_OVER, 0.5f));
        tl.draw(g2, (float) 20, (float) 30);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
