package topicevolutionvis.topic;

import topicevolutionvis.projection.temporal.TemporalProjection;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class CovarianceTopicSettings extends javax.swing.JDialog {

    private static CovarianceTopicSettings instance;
    private TemporalProjection tprojection;

    /** Creates new form CovarianceTopicSettings */
    private CovarianceTopicSettings(javax.swing.JDialog parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        cancekButton = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        percentageTermsLabel = new javax.swing.JLabel();
        percentageTopicsLabel = new javax.swing.JLabel();
        percentageTermsTextField = new javax.swing.JTextField();
        percentageTopicsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Covariance Topics Settings");
        setModal(true);

        closeButton.setText("Ok");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        cancekButton.setText("Cancel");
        cancekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancekButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancekButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        parametersPanel.setLayout(new java.awt.GridBagLayout());

        percentageTermsLabel.setText("Percentage terms:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(percentageTermsLabel, gridBagConstraints);

        percentageTopicsLabel.setText("Percentage topics:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(percentageTopicsLabel, gridBagConstraints);

        percentageTermsTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(percentageTermsTextField, gridBagConstraints);

        percentageTopicsTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(percentageTopicsTextField, gridBagConstraints);

        getContentPane().add(parametersPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    this.refreshData();
    this.setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

private void cancekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancekButtonActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_cancekButtonActionPerformed

    public static CovarianceTopicSettings getInstance(javax.swing.JDialog parent) {
        if (instance == null || instance.getParent() != parent) {
            instance = new CovarianceTopicSettings(parent);
        }

        return instance;
    }

    public void display(TemporalProjection tprojection) {
        this.tprojection = tprojection;

        TopicData tdata = tprojection.getTopicData();
        this.percentageTermsTextField.setText(Float.toString(tdata.getCovariancePercentageTerms()));
        this.percentageTopicsTextField.setText(Float.toString(tdata.getCovariancePercentageTopics()));

        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }

    private void refreshData() {
        TopicData tdata = tprojection.getTopicData();
        tdata.setCovariancePercentageTerms(Float.parseFloat(this.percentageTermsTextField.getText()));
        tdata.setCovariancePercentageTopics(Float.parseFloat(this.percentageTopicsTextField.getText()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancekButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JLabel percentageTermsLabel;
    private javax.swing.JTextField percentageTermsTextField;
    private javax.swing.JLabel percentageTopicsLabel;
    private javax.swing.JTextField percentageTopicsTextField;
    // End of variables declaration//GEN-END:variables
}
