/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboudDialog.java
 *
 * Created on 30/04/2009, 14:37:25
 */
package topicevolutionvis.view;

/**
 *
 * @author Aretha
 */
public class AboutDialog extends javax.swing.JDialog {

    private String version = "0.1.0";

    /** Creates new form AboudDialog */
    public AboutDialog() {
        super(ScienceViewMainFrame.getInstance());
        this.setLocationRelativeTo(null);
        initComponents();
        createMessage();
        

    }

    private void createMessage() {
        StringBuilder message = new StringBuilder("<p style=\"word-spacing: 0; margin: 0\"><b><font size=\"5\" color=\"#0000FF\" face=\"Verdana\">Topic Evolution Visualization (version ");
        message = message.append(version).append(")</font></b></p><p style=\"word-spacing: 0; margin: 0\"><b><font face=\"Verdana\" size=\"4\">University of São Paulo (USP), São Carlos/SP, Brazil</font></b></p><p style=\"word-spacing: 0; margin: 0\"><b><font face=\"Verdana\" size=\"3\">Matemathical and Computer Science Institute (ICMC)</font></b></p><p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">Computer Graphics and Image Processing Group</font></p><p style=\"word-spacing: 0; margin: 0\">&nbsp;</p><p style=\"word-spacing: 0; margin: 0\">&nbsp;</p><p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\"><b>Developer:</b></font></p><p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Aretha Barbosa Alencar (aretha@icmc.usp.br)</font></p><p style=\"word-spacing: 0; margin: 0\">&nbsp;</p><p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\"><b>Supervisor</b>:</font></p><p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Maria Cristina Ferreira de Oliveira (cristina@icmc.usp.br)</font></p>");
        this.aboutEditorPane.setText(message.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutScrollPane = new javax.swing.JScrollPane();
        aboutEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setMinimumSize(new java.awt.Dimension(500, 300));

        aboutEditorPane.setContentType("text/html");
        aboutEditorPane.setEditable(false);
        aboutEditorPane.setMinimumSize(new java.awt.Dimension(300, 200));
        aboutEditorPane.setPreferredSize(new java.awt.Dimension(300, 200));
        aboutScrollPane.setViewportView(aboutEditorPane);

        getContentPane().add(aboutScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane aboutEditorPane;
    private javax.swing.JScrollPane aboutScrollPane;
    // End of variables declaration//GEN-END:variables
}
